#ifndef APPLICATION_MODE_LONGLIFE_H
#define APPLICATION_MODE_LONGLIFE_H

#define APP_FW_VARIANT "+longlife"

#define APP_SENSOR_POWER_PROFILING_ENABLED (1U)

#define APP_HEARTBEAT_INTERVAL_MS (3U * 60U * 1000U)

#define APP_BLE_INTERVAL_MS (APP_HEARTBEAT_INTERVAL_MS)

#define APP_NUM_REPEATS (0U)

#define APP_NFC_ENABLED (0U)

#define APP_GATT_ENABLED (0U)

#define RT_FLASH_ENABLED (0U)

#define APP_SENSOR_ENVIRONMENTAL_MCU_ENABLED (0U)
#define APP_SENSOR_NTC_ENABLED (0U)
#define APP_SENSOR_PHOTO_ENABLED (0U)

#define APP_SENSOR_BME280_ENABLED RB_ENVIRONMENTAL_BME280_PRESENT
#define APP_SENSOR_BME280_MODE RD_SENSOR_CFG_SLEEP

#define APP_SENSOR_DPS310_ENABLED RB_ENVIRONMENTAL_DPS310_PRESENT
#define APP_SENSOR_DPS310_MODE RD_SENSOR_CFG_SLEEP
#define RI_DPS310_SPI_ENABLED RB_ENVIRONMENTAL_DPS310_SPI_USE

#define APP_SENSOR_SHTCX_ENABLED RB_ENVIRONMENTAL_SHTCX_PRESENT
#define APP_SENSOR_SHTCX_MODE RD_SENSOR_CFG_SLEEP

#define APP_SENSOR_TMP117_ENABLED RB_ENVIRONMENTAL_TMP117_PRESENT
#define APP_SENSOR_TMP117EXT_ENABLED RB_ENVIRONMENTAL_TMP117EXT_PRESENT
#define APP_SENSOR_TMP117_MODE RD_SENSOR_CFG_SLEEP

#define APP_SENSOR_STHS34PF80_ENABLED RB_ENVIRONMENTAL_STHS34PF80_PRESENT
#define APP_SENSOR_STHS34PF80_MODE RD_SENSOR_CFG_SLEEP

#define APP_SENSOR_LIS2DH12_MODE RD_SENSOR_CFG_SLEEP
#define APP_SENSOR_LIS2DH12_SAMPLERATE RD_SENSOR_CFG_CUSTOM_3 //!< 1344 Hz in normal mode.

#define APP_SENSOR_MMC5616WA_MODE RD_SENSOR_CFG_SLEEP
#define APP_SENSOR_MMC5616WA_SAMPLERATE RD_SENSOR_CFG_CUSTOM_1 //!< 255 Hz.

#endif
