#ifndef APPLICATION_MODE_LONGLIFE_H
#define APPLICATION_MODE_LONGLIFE_H

#define APP_FW_VARIANT "+extralife"

#define APP_BLE_INTERVAL_MS (1285U * 7U) //8995 ms, longest allowed divisible by 1285

#define APP_NUM_REPEATS (6U) // ~54 s

#define APP_GATT_ENABLED (0U)

#define RT_FLASH_ENABLED (0U)

#define APP_SENSOR_TMP117_SAMPLERATE RD_SENSOR_CFG_CUSTOM_2 // 8000 ms conversion cycle.

#define APP_SENSOR_LIS2DH12_ENABLED RB_ACCELEROMETER_LIS2DH12_PRESENT

#define APP_SENSOR_LIS2DH12_DSP_FUNC RD_SENSOR_DSP_LAST

#define APP_SENSOR_LIS2DH12_DSP_PARAM (1U)

#define APP_SENSOR_LIS2DH12_MODE RD_SENSOR_CFG_SLEEP

#define APP_SENSOR_LIS2DH12_RESOLUTION (8U) //!< bits

#define APP_SENSOR_LIS2DH12_SAMPLERATE (1U) //!< Hz

#define APP_SENSOR_LIS2DH12_SCALE (2U) //!< G



#endif