name: Build Firmware

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build firmware
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          submodules: recursive

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          python --version
          pip --version
          python3 -m pip install --upgrade pip
          pip3 install -r scripts/requirements.txt

      - name: Install nRF Command Line Tools
        run: |
          wget -q -P ~ https://storage.ruuvi.com/nrf-command-line-tools_10.24.2_amd64.deb
          sudo dpkg -i ~/nrf-command-line-tools_10.24.2_amd64.deb
          rm -f ~/nrf-command-line-tools_10.24.2_amd64.deb

      - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '7-2018-q2'

      - name: Create symbolic link for ARM toolchain
        run: |
          sudo ln -s /home/runner/gcc-arm-none-eabi-7.2018.2-linux-x64/gcc-arm-none-eabi-7-2018-q2-update \
            /usr/local/gcc-arm-none-eabi-7-2018-q2-update

      - name: Cache nRF5_SDK_15.3.0_59ac345
        id: cache-nRF5_SDK
        uses: actions/cache@v4
        with:
          path: ~/nRF5_SDK_15.3.0_59ac345
          key: nRF5_SDK-${{ hashFiles('.github/workflows/build-fw.yml') }}

      - name: Download and install Nordic SDK nRF5_SDK_15.3.0_59ac345
        if: steps.cache-nRF5_SDK.outputs.cache-hit != 'true'
        run: |
          wget -q -P ~ https://storage.ruuvi.com/nRF5_SDK_15.3.0_59ac345.zip
          unzip -q ~/nRF5_SDK_15.3.0_59ac345.zip -d ~
          rm -f ~/nRF5_SDK_15.3.0_59ac345.zip

      - name: Get short commit hash if no tags
        id: get-version
        run: |
          VERSION=$(git describe --exact-match --tags HEAD 2>/dev/null || git rev-parse --short HEAD)
          echo "git_version=$VERSION" >> $GITHUB_ENV

      - name: Run build
        run: |
          ln -s ~/nRF5_SDK_15.3.0_59ac345 nRF5_SDK_15.3.0_59ac345
          cd src
          make ruuvitag_b

      - name: Generate artifact names
        id: artifact-names
        run: |
          PREFIX_B="ruuvitag_b_armgcc_ruuvifw"
          PREFIX_C="ruuvitag_c_armgcc_ruuvifw"
          VERSION="${{ env.git_version }}"
          DEFAULT="default"
          LLIFE="longlife"
          TEST="test"
          UUID="uuid"
          DEFAULT_B_NAME="${PREFIX_B}_${DEFAULT}_${VERSION}"
          LLIFE_B_NAME="${PREFIX_B}_${LLIFE}_${VERSION}"
          TEST_B_NAME="${PREFIX_B}_${TEST}_${VERSION}"
          UUID_B_NAME="${PREFIX_B}_${UUID}_${VERSION}"
          DEFAULT_C_NAME="${PREFIX_C}_${DEFAULT}_${VERSION}"
          LLIFE_C_NAME="${PREFIX_C}_${LLIFE}_${VERSION}"
          TEST_C_NAME="${PREFIX_C}_${TEST}_${VERSION}"
          UUID_C_NAME="${PREFIX_C}_${UUID}_${VERSION}"
          BUILDPATH="src/targets/ruuvitag_b/armgcc"
          
          echo "all_artifacts=${VERSION}_binaries" >> $GITHUB_ENV
          echo "default_b_full_hex=${DEFAULT_B_NAME}_full.hex" >> $GITHUB_ENV
          echo "default_b_app_dfu=${DEFAULT_B_NAME}_dfu_app.zip" >> $GITHUB_ENV
          echo "llife_b_full_hex=${LLIFE_B_NAME}_full.hex" >> $GITHUB_ENV
          echo "llife_b_app_dfu=${LLIFE_B_NAME}_dfu_app.zip" >> $GITHUB_ENV
          echo "uuid_b_full_hex=${UUID_B_NAME}_full.hex" >> $GITHUB_ENV
          echo "uuid_b_app_dfu=${UUID_B_NAME}_dfu_app.zip" >> $GITHUB_ENV
          echo "test_b_full_hex=${TEST_B_NAME}_full.hex" >> $GITHUB_ENV
          echo "test_b_app_dfu=${TEST_B_NAME}_dfu_app.zip" >> $GITHUB_ENV
          echo "default_c_full_hex=${DEFAULT_B_NAME}_full.hex" >> $GITHUB_ENV
          echo "default_c_app_dfu=${DEFAULT_B_NAME}_dfu_app.zip" >> $GITHUB_ENV
          echo "llife_c_full_hex=${LLIFE_B_NAME}_full.hex" >> $GITHUB_ENV
          echo "llife_c_app_dfu=${LLIFE_B_NAME}_dfu_app.zip" >> $GITHUB_ENV
          echo "uuid_c_full_hex=${UUID_B_NAME}_full.hex" >> $GITHUB_ENV
          echo "uuid_c_app_dfu=${UUID_B_NAME}_dfu_app.zip" >> $GITHUB_ENV
          echo "test_c_full_hex=${TEST_B_NAME}_full.hex" >> $GITHUB_ENV
          echo "test_c_app_dfu=${TEST_B_NAME}_dfu_app.zip" >> $GITHUB_ENV
          echo "buildpath=${BUILDPATH}" >> $GITHUB_ENV

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.all_artifacts }}
          path: |
            ${{ env.buildpath }}/${{ env.default_b_full_hex }}
            ${{ env.buildpath }}/${{ env.default_b_app_dfu }}
            ${{ env.buildpath }}/${{ env.llife_b_full_hex }}
            ${{ env.buildpath }}/${{ env.llife_b_app_dfu }}
            ${{ env.buildpath }}/${{ env.test_b_full_hex }}
            ${{ env.buildpath }}/${{ env.test_b_app_dfu }}
            ${{ env.buildpath }}/${{ env.uuid_b_full_hex }}
            ${{ env.buildpath }}/${{ env.uuid_b_app_dfu }}
            ${{ env.buildpath }}/${{ env.default_c_full_hex }}
            ${{ env.buildpath }}/${{ env.default_c_app_dfu }}
            ${{ env.buildpath }}/${{ env.llife_c_full_hex }}
            ${{ env.buildpath }}/${{ env.llife_c_app_dfu }}
            ${{ env.buildpath }}/${{ env.test_c_full_hex }}
            ${{ env.buildpath }}/${{ env.test_c_app_dfu }}
            ${{ env.buildpath }}/${{ env.uuid_c_full_hex }}
            ${{ env.buildpath }}/${{ env.uuid_c_app_dfu }}
