# Run Ceedling tests

name: Ceedling

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "unit-test"
  unit-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.1.1

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6

    # Runs a single command using the runners shell
    - name: Install Ceedling
      run: gem install ceedling

    - name: Download Nordic SDK
      run: |
        if [ ! -d "nRF5_SDK_15.3.0_59ac345/modules" ]; then
          wget -q https://developer.nordicsemi.com/nRF5_SDK/nRF5_SDK_v15.x.x/nRF5_SDK_15.3.0_59ac345.zip
          unzip -q nRF5_SDK_15.3.0_59ac345.zip
        fi

    # Runs a set of commands using the runners shell
    - name: Run unit tests
      run: |
        ceedling test:all
