# This is a basic workflow to help you get started with Actions

name: PVS-Studio-Check

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  doxygen:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.1.1

    # Generate folder for PVS report
    - name: mkdir
      run: mkdir -p doxygen/html

    - name: Install PVS Studio
      run: |
          wget -q -O - https://files.viva64.com/etc/pubkey.txt | sudo apt-key add -
          sudo wget https://files.viva64.com/etc/viva64.list -O /etc/apt/sources.list.d/viva64.list
          sudo apt-get update -qq && sudo apt-get install --assume-yes --quiet gcc-multilib && sudo apt-get install -qq
          sudo apt-get install -qq pvs-studio
          pvs-studio-analyzer credentials  ${{ secrets.PVS_USERNAME }} ${{ secrets.PVS_KEY }}

    - name: Run PVS Studio
      run: make pvs

    # Error if pvs.error has content
    - name: Check PVS has no errors
      run: |
          if [[ $(wc -l < pvs.error) -gt 1 ]]
          then
              cat pvs.error
              exit 1
          fi